version: '3.4'

services:
  realtimeorders.api:
    image: ${DOCKER_REGISTRY-}realtimeordersapi    
    depends_on:
      - redis_db      
    build:
      context: .
      dockerfile: RealtimeOrders.API/Dockerfile
    ports:
      - "32778:443"
      - "32775:80"

  redis_db:
    image: ${DOCKER_REGISTRY-}redis
    ports:
       - "6379:6379"